service: acme-service
frameworkVersion: '3'
package:
  individually: true
  patterns:
    - '!node_modules/**'
    - index.js

plugins:
  - serverless-localstack
  - ./dist/index.js

custom:
  localstack:
    stages:
      - dev  
  exports:
    environment:
      file: .serverless/.env.${sls:stage}
      format: env
      overwrite: true    
    stack:
      file: .serverless/stack-outputs.txt
      format: env
      overwrite: true    

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
    FOO: bar
    STAGE: ${sls:stage}
    REGION: ${aws:region}
    SERVICE: ${self:service}

functions:
  hello:
    handler: index.handler

resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-bucket
  Outputs:
    Foo:
      Value: bar
    BucketName:
      Value: !Ref bucket
